/**
 * Terms of Service page.
 */
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import { BRAND } from "@/lib/branding";

export default function Terms() {
  const navigate = useNavigate();
  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 border-b border-border/40 bg-background/80 backdrop-blur-md">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-4 py-3">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <BrandLogo size="sm" />
        </div>
      </nav>

      <article className="mx-auto max-w-3xl px-4 py-10 prose prose-sm dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground"><em>Last updated: March {year}</em></p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using {BRAND.name} ("the Service"), you agree to be bound by these Terms of
          Service. If you do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          {BRAND.name} is an AI-powered job application toolkit that generates tailored resumes,
          cover letters, and supporting materials. The Service is provided "as is" and may be
          updated or modified at any time.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You must provide accurate information when creating an account. You are responsible for
          maintaining the confidentiality of your credentials and for all activities under your
          account. New accounts require administrative approval before full access is granted.
        </p>

        <h2>4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for unlawful purposes or to misrepresent your qualifications</li>
          <li>Attempt to reverse-engineer, scrape, or overload the Service</li>
          <li>Share your account credentials with third parties</li>
          <li>Upload malicious content or attempt to compromise system security</li>
        </ul>

        <h2>5. AI-Generated Content</h2>
        <p>
          Content generated by the Service is created using artificial intelligence and is intended
          as a starting point. You are solely responsible for reviewing, verifying, and customizing
          all generated materials before use. {BRAND.name} does not guarantee the accuracy,
          completeness, or suitability of AI-generated content.
        </p>

        <h2>6. Intellectual Property</h2>
        <p>
          You retain ownership of the content you provide (resume text, job descriptions, etc.).
          Materials generated by the Service based on your input are yours to use. The Service
          itself, including its design, code, and branding, remains the property of {BRAND.name}.
        </p>

        <h2>7. Subscriptions & Billing</h2>
        <p>
          Certain features require a paid subscription. Subscription terms, pricing, and renewal
          policies are displayed at the time of purchase. Refund requests are handled on a
          case-by-case basis.
        </p>

        <h2>8. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, {BRAND.name} and its operators shall not be liable
          for any indirect, incidental, or consequential damages arising from your use of the
          Service, including but not limited to loss of employment opportunities.
        </p>

        <h2>9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account at any time for violation of
          these Terms. You may delete your account at any time through your account settings.
        </p>

        <h2>10. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of the Service after changes
          constitutes acceptance of the updated Terms.
        </p>

        <h2>11. Contact</h2>
        <p>
          For questions about these Terms, please reach out through the support channels available
          within the application.
        </p>
      </article>

      <footer className="border-t border-border/60 py-6 text-center text-xs text-muted-foreground">
        {BRAND.copyright(year)}
      </footer>
    </div>
  );
}
