/**
 * Fixed JavaScript rendering engine for dashboards.
 * Reads window.__DASHBOARD_DATA__ (JSON) and builds the entire dashboard DOM.
 * This file is NEVER regenerated by the LLM — only data changes.
 */

export function getScriptsJs(): string {
  return `
(function() {
  'use strict';

  // === SEEDED PRNG (mulberry32) ===
  function mulberry32(a) {
    return function() {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      var t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }

  // === DATA GENERATORS ===
  var FIRST_NAMES = ['James','Mary','Robert','Patricia','John','Jennifer','Michael','Linda','David','Elizabeth','William','Barbara','Richard','Susan','Joseph','Jessica','Thomas','Sarah','Christopher','Karen','Charles','Lisa','Daniel','Nancy','Matthew','Betty','Anthony','Margaret','Mark','Sandra','Donald','Ashley','Steven','Kimberly','Andrew','Emily','Paul','Donna','Joshua','Michelle','Kenneth','Carol','Kevin','Amanda','Brian','Dorothy','George','Melissa','Timothy','Deborah'];
  var LAST_NAMES = ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson'];
  var REGIONS_DEFAULT = ['North America','EMEA','APAC','LATAM','ANZ','DACH','Nordics','UK','Southeast Asia','India'];

  var generators = {
    personName: function(rng) {
      return FIRST_NAMES[Math.floor(rng() * FIRST_NAMES.length)] + ' ' + LAST_NAMES[Math.floor(rng() * LAST_NAMES.length)];
    },
    company: function(rng, cfg) {
      var opts = cfg.options || ['Acme Corp','Globex Inc','Initech','Umbrella Co','Wayne Enterprises','Stark Industries','Oscorp','LexCorp'];
      return opts[Math.floor(rng() * opts.length)];
    },
    email: function(rng) {
      var name = FIRST_NAMES[Math.floor(rng() * FIRST_NAMES.length)].toLowerCase();
      var domains = ['gmail.com','company.com','enterprise.io','corp.net','mail.com'];
      return name + Math.floor(rng() * 999) + '@' + domains[Math.floor(rng() * domains.length)];
    },
    date: function(rng, cfg) {
      var days = cfg.maxDays || 365;
      var d = new Date();
      d.setDate(d.getDate() - Math.floor(rng() * days));
      return d.toISOString().split('T')[0];
    },
    futureDate: function(rng, cfg) {
      var days = cfg.maxDays || 180;
      var d = new Date();
      d.setDate(d.getDate() + Math.floor(rng() * days));
      return d.toISOString().split('T')[0];
    },
    currency: function(rng, cfg) {
      var min = cfg.min || 1000;
      var max = cfg.max || 100000;
      var val = Math.floor(min + rng() * (max - min));
      return '$' + val.toLocaleString('en-US');
    },
    integer: function(rng, cfg) {
      var min = cfg.min || 0;
      var max = cfg.max || 100;
      return Math.floor(min + rng() * (max - min));
    },
    percent: function(rng, cfg) {
      var min = cfg.min || 0;
      var max = cfg.max || 100;
      return (min + rng() * (max - min)).toFixed(1) + '%';
    },
    pick: function(rng, cfg) {
      var opts = cfg.options || ['Option A','Option B','Option C'];
      return opts[Math.floor(rng() * opts.length)];
    },
    status: function(rng, cfg) {
      var opts = cfg.options || ['Active','Pending','Closed','At Risk'];
      return opts[Math.floor(rng() * opts.length)];
    },
    region: function(rng, cfg) {
      var opts = cfg.options || REGIONS_DEFAULT;
      return opts[Math.floor(rng() * opts.length)];
    },
    product: function(rng, cfg) {
      var opts = cfg.options || ['Enterprise','Professional','Starter','Growth'];
      return opts[Math.floor(rng() * opts.length)];
    }
  };

  function generateTableRows(config) {
    var rng = mulberry32(config.seed || 42);
    var rows = [];
    for (var i = 0; i < config.count; i++) {
      var row = {};
      var fields = config.fields;
      for (var key in fields) {
        if (fields.hasOwnProperty(key)) {
          var gen = generators[fields[key].type];
          row[key] = gen ? gen(rng, fields[key]) : '';
        }
      }
      rows.push(row);
    }
    return rows;
  }

  // === DOM HELPERS ===
  function el(tag, attrs) {
    var elem = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        if (k === 'className') elem.className = attrs[k];
        else if (k === 'onclick') elem.onclick = attrs[k];
        else if (k === 'innerHTML') elem.innerHTML = attrs[k];
        else elem.setAttribute(k, attrs[k]);
      }
    }
    for (var i = 2; i < arguments.length; i++) {
      var child = arguments[i];
      if (!child) continue;
      if (typeof child === 'string') elem.appendChild(document.createTextNode(child));
      else elem.appendChild(child);
    }
    return elem;
  }

  // === BRANDING ===
  function applyBranding(b) {
    var s = document.documentElement.style;
    s.setProperty('--md-primary', b.primary || '#6750A4');
    s.setProperty('--md-on-primary', b.onPrimary || '#FFFFFF');
    s.setProperty('--md-primary-container', b.primaryContainer || '#EADDFF');
    s.setProperty('--md-on-primary-container', b.onPrimaryContainer || '#21005E');
    s.setProperty('--md-secondary', b.secondary || '#625B71');
    s.setProperty('--md-on-secondary', b.onSecondary || '#FFFFFF');
    s.setProperty('--md-surface', b.surface || '#FEF7FF');
    s.setProperty('--md-on-surface', b.onSurface || '#1D1B20');
    s.setProperty('--md-surface-variant', b.surfaceVariant || '#E7E0EC');
    s.setProperty('--md-outline', b.outline || '#79747E');
    s.setProperty('--md-error', b.error || '#B3261E');
    if (b.fontHeading) {
      s.setProperty('--font-heading', "'" + b.fontHeading + "', sans-serif");
      var link = document.createElement('link');
      link.href = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(b.fontHeading) + ':wght@400;500;600;700&display=swap';
      link.rel = 'stylesheet';
      document.head.appendChild(link);
    }
    if (b.fontBody && b.fontBody !== b.fontHeading) {
      s.setProperty('--font-body', "'" + b.fontBody + "', sans-serif");
      var link2 = document.createElement('link');
      link2.href = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(b.fontBody) + ':wght@400;500&display=swap';
      link2.rel = 'stylesheet';
      document.head.appendChild(link2);
    }
  }

  // === NAVIGATION ===
  function buildNavigation(nav, meta) {
    var header = document.getElementById('sidebar-header');
    header.appendChild(el('h2', {}, meta.companyName || 'Dashboard'));
    header.appendChild(el('p', {}, meta.jobTitle || ''));

    var navEl = document.getElementById('sidebar-nav');
    nav.forEach(function(item) {
      var link = el('a', { className: 'nav-link', 'data-section': item.id, href: '#' },
        el('span', { className: 'material-icons-outlined' }, item.icon || 'dashboard'),
        el('span', { className: 'nav-label' }, item.label)
      );
      link.addEventListener('click', function(e) {
        e.preventDefault();
        showSection(item.id);
        document.querySelectorAll('.nav-link').forEach(function(l) { l.classList.remove('active'); });
        this.classList.add('active');
        if (window.innerWidth <= 768) {
          document.getElementById('sidebar').classList.add('collapsed');
        }
      });
      navEl.appendChild(link);
    });

    document.getElementById('page-title').textContent = meta.companyName + ' \\u2014 ' + meta.department + ' Dashboard';
  }

  function showSection(id) {
    document.querySelectorAll('.dashboard-section').forEach(function(s) { s.style.display = 'none'; });
    var target = document.getElementById('section-' + id);
    if (target) target.style.display = 'block';
    setTimeout(function() {
      if (typeof Chart !== 'undefined') {
        Object.keys(Chart.instances).forEach(function(key) {
          Chart.instances[key].resize();
        });
      }
    }, 50);
  }

  // === RENDER METRICS ===
  function renderMetrics(container, metrics) {
    if (!metrics || !metrics.length) return;
    var grid = el('div', { className: 'metrics-grid' });
    metrics.forEach(function(m) {
      var card = el('div', { className: 'metric-card' });
      card.appendChild(el('span', { className: 'metric-label' }, m.label));
      card.appendChild(el('span', { className: 'metric-value' }, m.value));
      if (m.change) {
        card.appendChild(el('span', { className: 'metric-change ' + (m.trend || 'neutral') }, m.change));
      }
      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  // === CROSS-CHART FILTERING ===
  var sectionCharts = {};
  var sectionTables = [];

  // === DIMENSION ALIASES — maps filter IDs to possible column keys / label words ===
  var DIMENSION_ALIASES = {
    region: ['region','geo','geography','country','location','market','territory','area'],
    quarter: ['quarter','qtr','period','time','date','year','month'],
    product: ['product','offering','solution','tier','plan','package','sku','line'],
    segment: ['segment','vertical','industry','sector','category'],
    department: ['department','dept','team','division','org','unit'],
    status: ['status','state','stage','phase','health'],
    priority: ['priority','severity','urgency','level'],
    type: ['type','kind','class','classification']
  };

  function getDimensionKeys(filterId) {
    var id = filterId.toLowerCase();
    if (DIMENSION_ALIASES[id]) return DIMENSION_ALIASES[id];
    // fallback: the filter id itself plus common suffixes stripped
    return [id, id.replace(/_/g, ' '), id.replace(/-/g, ' ')];
  }

  function findMatchingColumnIndex(columns, filterId) {
    var keys = getDimensionKeys(filterId);
    for (var ci = 0; ci < columns.length; ci++) {
      var colKey = (columns[ci].key || '').toLowerCase();
      var colLabel = (columns[ci].label || '').toLowerCase();
      for (var ki = 0; ki < keys.length; ki++) {
        if (colKey === keys[ki] || colLabel === keys[ki] ||
            colKey.indexOf(keys[ki]) !== -1 || colLabel.indexOf(keys[ki]) !== -1) {
          return ci;
        }
      }
    }
    return -1;
  }

  function valueMatchesFilter(cellValue, filterValue) {
    if (!cellValue || !filterValue) return false;
    var cv = String(cellValue).toLowerCase().trim();
    var fv = filterValue.toLowerCase().trim();
    if (cv === fv) return true;
    // Check if cell contains filter value as a word
    if (cv.indexOf(fv) !== -1) return true;
    // Check if filter value is an abbreviation of cell value (e.g., "US" → "United States")
    return false;
  }

  function addAlpha(color, alpha) {
    if (!color) return color;
    if (color.indexOf('rgba') === 0) return color.replace(/,[^,]+\\)$/, ', ' + alpha + ')');
    if (color.indexOf('rgb(') === 0) return color.replace('rgb(', 'rgba(').replace(')', ', ' + alpha + ')');
    if (color.indexOf('hsl(') === 0) return color.replace('hsl(', 'hsla(').replace(')', ', ' + alpha + ')');
    if (color.indexOf('#') === 0) {
      var hex = color.slice(1);
      if (hex.length === 3) hex = hex[0]+hex[0]+hex[1]+hex[1]+hex[2]+hex[2];
      return 'rgba(' + parseInt(hex.slice(0,2),16) + ',' + parseInt(hex.slice(2,4),16) + ',' + parseInt(hex.slice(4,6),16) + ',' + alpha + ')';
    }
    return color;
  }

  function applyCrossFilter(sectionId, label, sourceChartId) {
    var charts = sectionCharts[sectionId];
    if (!charts) return;
    charts.forEach(function(entry) {
      var badge = entry.card.querySelector('.chart-filter-badge');
      if (badge) badge.remove();
      entry.card.classList.remove('filtered-dimmed', 'filtered-active');

      if (entry.id === sourceChartId) {
        entry.card.classList.add('filtered-active');
        var srcBadge = el('div', { className: 'chart-filter-badge' });
        srcBadge.appendChild(document.createTextNode('Filtering by: ' + label));
        var clearBtn = el('button', { onclick: function(e) { e.stopPropagation(); clearCrossFilter(sectionId); } }, '\\u00D7');
        srcBadge.appendChild(clearBtn);
        var h3s = entry.card.querySelector('h3');
        if (h3s) h3s.after(srcBadge); else entry.card.prepend(srcBadge);
        return;
      }

      var labels = entry.originalData.labels;
      var matchIdx = -1;
      for (var i = 0; i < labels.length; i++) { if (labels[i] === label) { matchIdx = i; break; } }

      if (matchIdx === -1) { entry.card.classList.add('filtered-dimmed'); return; }

      var inst = entry.instance;
      if (!inst) return;

      var compBadge = el('div', { className: 'chart-filter-badge' });
      compBadge.appendChild(document.createTextNode('Filtered: ' + label));
      var clrBtn = el('button', { onclick: function(e) { e.stopPropagation(); clearCrossFilter(sectionId); } }, '\\u00D7');
      compBadge.appendChild(clrBtn);
      var h3c = entry.card.querySelector('h3');
      if (h3c) h3c.after(compBadge); else entry.card.prepend(compBadge);

      inst.data.datasets.forEach(function(ds, dsIdx) {
        var origDs = entry.originalData.datasets[dsIdx];
        if (!origDs) return;
        if (Array.isArray(origDs.backgroundColor)) {
          ds.backgroundColor = origDs.backgroundColor.map(function(c, i) { return i === matchIdx ? c : addAlpha(c, 0.12); });
        } else if (typeof origDs.backgroundColor === 'string') {
          ds.backgroundColor = labels.map(function(_, i) { return i === matchIdx ? origDs.backgroundColor : addAlpha(origDs.backgroundColor, 0.12); });
        }
      });
      inst.update('none');
    });
  }

  function clearCrossFilter(sectionId) {
    var charts = sectionCharts[sectionId];
    if (!charts) return;
    charts.forEach(function(entry) {
      var badge = entry.card.querySelector('.chart-filter-badge');
      if (badge) badge.remove();
      entry.card.classList.remove('filtered-dimmed', 'filtered-active');
      var inst = entry.instance;
      if (!inst) return;
      inst.data.datasets.forEach(function(ds, dsIdx) {
        var origDs = entry.originalData.datasets[dsIdx];
        if (!origDs) return;
        if (origDs.backgroundColor) ds.backgroundColor = JSON.parse(JSON.stringify(origDs.backgroundColor));
      });
      inst.update('none');
    });
  }

  // === GLOBAL FILTER STATE ===
  var globalFilterState = {};
  var globalFilterDefs = [];

  function buildGlobalFilterBar(filters) {
    if (!filters || !filters.length) return;
    globalFilterDefs = filters;
    var bar = el('div', { className: 'global-filter-bar' });
    filters.forEach(function(f) {
      // Ensure "All" is first option
      if (f.options && f.options.length && f.options[0] !== 'All') {
        f.options = ['All'].concat(f.options);
      }
      var group = el('div', { className: 'gf-group' });
      group.appendChild(el('span', { className: 'gf-label' }, f.label));

      if (f.type === 'dropdown') {
        var select = document.createElement('select');
        select.className = 'gf-select';
        f.options.forEach(function(opt) {
          var option = document.createElement('option');
          option.value = opt;
          option.textContent = opt;
          select.appendChild(option);
        });
        select.addEventListener('change', function() {
          globalFilterState[f.id] = this.value;
          applyGlobalFilters();
        });
        globalFilterState[f.id] = f.options[0];
        group.appendChild(select);
      } else if (f.type === 'segmented') {
        var wrap = el('div', { className: 'gf-segmented' });
        f.options.forEach(function(opt, idx) {
          var btn = el('button', { className: 'gf-seg-btn' + (idx === 0 ? ' active' : ''), 'data-value': opt }, opt);
          btn.addEventListener('click', function() {
            wrap.querySelectorAll('.gf-seg-btn').forEach(function(b) { b.classList.remove('active'); });
            this.classList.add('active');
            globalFilterState[f.id] = opt;
            applyGlobalFilters();
          });
          wrap.appendChild(btn);
        });
        globalFilterState[f.id] = f.options[0];
        group.appendChild(wrap);
      } else if (f.type === 'chips') {
        var wrap = el('div', { className: 'gf-chips' });
        f.options.forEach(function(opt, idx) {
          var chip = el('button', { className: 'gf-chip' + (idx === 0 ? ' active' : ''), 'data-value': opt }, opt);
          chip.addEventListener('click', function() {
            wrap.querySelectorAll('.gf-chip').forEach(function(b) { b.classList.remove('active'); });
            this.classList.add('active');
            globalFilterState[f.id] = opt;
            applyGlobalFilters();
          });
          wrap.appendChild(chip);
        });
        globalFilterState[f.id] = f.options[0];
        group.appendChild(wrap);
      }

      bar.appendChild(group);
    });
    var topBar = document.getElementById('top-bar');
    topBar.after(bar);
  }

  function applyGlobalFilters() {
    var activeFilters = [];
    for (var k in globalFilterState) {
      if (globalFilterState.hasOwnProperty(k)) {
        var v = globalFilterState[k];
        if (v && v !== 'All') activeFilters.push({ id: k, value: v });
      }
    }

    // --- Reset everything when no filters active ---
    if (!activeFilters.length) {
      for (var sid in sectionCharts) {
        if (sectionCharts.hasOwnProperty(sid)) {
          sectionCharts[sid].forEach(function(entry) {
            entry.card.classList.remove('filtered-dimmed', 'filtered-dimmed-global');
            var badge = entry.card.querySelector('.chart-filter-badge');
            if (badge) badge.remove();
            if (entry.resetFilter) { entry.resetFilter(); return; }
            var inst = entry.instance;
            if (!inst) return;
            inst.data = JSON.parse(JSON.stringify(entry.originalData));
            inst.update('none');
          });
        }
      }
      sectionTables.forEach(function(entry) {
        rebuildTableRows(entry, entry.originalRows);
      });
      return;
    }

    // --- FILTER CHARTS (true data filtering) ---
    for (var sid in sectionCharts) {
      if (!sectionCharts.hasOwnProperty(sid)) continue;
      sectionCharts[sid].forEach(function(entry) {
        entry.card.classList.remove('filtered-dimmed', 'filtered-dimmed-global');
        var badge = entry.card.querySelector('.chart-filter-badge');
        if (badge) badge.remove();

        // Custom filter callback (heatmap, funnel etc.)
        if (entry.applyFilter) {
          entry.applyFilter(activeFilters);
          return;
        }

        var inst = entry.instance;
        if (!inst) return;

        var origLabels = entry.originalData.labels || [];
        var origDatasets = entry.originalData.datasets || [];

        // Find which labels match ANY active filter value
        var matchingIndices = [];
        for (var li = 0; li < origLabels.length; li++) {
          var labelStr = String(origLabels[li]).toLowerCase();
          var matches = activeFilters.some(function(f) {
            return valueMatchesFilter(labelStr, f.value);
          });
          if (matches) matchingIndices.push(li);
        }

        // Also check if any dataset labels match
        var datasetMatches = [];
        origDatasets.forEach(function(ds, dsi) {
          var dsLabel = String(ds.label || '').toLowerCase();
          var matches = activeFilters.some(function(f) {
            return valueMatchesFilter(dsLabel, f.value);
          });
          if (matches) datasetMatches.push(dsi);
        });

        // If no label matches and no dataset matches, check if filter is even applicable
        if (matchingIndices.length === 0 && datasetMatches.length === 0) {
          // Check if any filter dimension relates to chart data at all
          var chartRelevant = false;
          var allText = origLabels.join(' ').toLowerCase() + ' ' + origDatasets.map(function(ds) { return ds.label || ''; }).join(' ').toLowerCase();
          activeFilters.forEach(function(f) {
            var keys = getDimensionKeys(f.id);
            keys.forEach(function(k) {
              if (allText.indexOf(k) !== -1) chartRelevant = true;
            });
          });
          // If the filter dimension isn't even relevant to this chart, skip (don't dim)
          if (!chartRelevant) {
            inst.data = JSON.parse(JSON.stringify(entry.originalData));
            inst.update('none');
            return;
          }
          // Relevant but no matches — dim entire chart
          entry.card.classList.add('filtered-dimmed-global');
          return;
        }

        // Filter by matching indices — rebuild chart with subset
        if (matchingIndices.length > 0 && matchingIndices.length < origLabels.length) {
          var newLabels = matchingIndices.map(function(i) { return origLabels[i]; });
          var newDatasets = origDatasets.map(function(ds) {
            var newDs = JSON.parse(JSON.stringify(ds));
            newDs.data = matchingIndices.map(function(i) { return ds.data[i]; });
            if (Array.isArray(ds.backgroundColor)) {
              newDs.backgroundColor = matchingIndices.map(function(i) { return ds.backgroundColor[i]; });
            }
            if (Array.isArray(ds.borderColor)) {
              newDs.borderColor = matchingIndices.map(function(i) { return ds.borderColor[i]; });
            }
            return newDs;
          });
          inst.data.labels = newLabels;
          inst.data.datasets = newDatasets;
        } else if (datasetMatches.length > 0 && datasetMatches.length < origDatasets.length) {
          // Filter by dataset matches
          inst.data.labels = JSON.parse(JSON.stringify(origLabels));
          inst.data.datasets = datasetMatches.map(function(dsi) {
            return JSON.parse(JSON.stringify(origDatasets[dsi]));
          });
        } else {
          // All match — restore original
          inst.data = JSON.parse(JSON.stringify(entry.originalData));
        }
        inst.update('none');
      });
    }

    // --- FILTER TABLES (true data filtering) ---
    sectionTables.forEach(function(entry) {
      var filteredRows = entry.originalRows.filter(function(row) {
        return activeFilters.every(function(f) {
          // Find the column that matches this filter dimension
          var colIdx = findMatchingColumnIndex(entry.columns, f.id);
          if (colIdx === -1) {
            // No matching column — check all columns for the value (broad match)
            var anyMatch = false;
            entry.columns.forEach(function(col) {
              if (valueMatchesFilter(String(row[col.key] || ''), f.value)) anyMatch = true;
            });
            return anyMatch;
          }
          var colKey = entry.columns[colIdx].key;
          return valueMatchesFilter(String(row[colKey] || ''), f.value);
        });
      });
      rebuildTableRows(entry, filteredRows);
    });
  }

  function rebuildTableRows(entry, rows) {
    entry.tbody.innerHTML = '';
    rows.forEach(function(row, idx) {
      var tr = el('tr', {});
      var labelParts = [];
      entry.columns.forEach(function(col) {
        var val = String(row[col.key] != null ? row[col.key] : '');
        tr.appendChild(el('td', {}, val));
        labelParts.push(val);
      });
      tr.setAttribute('data-labels', labelParts.join('|'));
      tr.setAttribute('data-row-idx', String(idx));
      tr.onclick = function() {
        var fields = entry.columns.map(function(col) {
          return { label: col.label, value: String(row[col.key] != null ? row[col.key] : '') };
        });
        showDrillDown(entry.title + ' \\u2014 Record #' + (idx + 1), fields);
      };
      entry.tbody.appendChild(tr);
    });
    // Apply any active column filters on top
    if (entry.columnFilters && Object.keys(entry.columnFilters).length) {
      applyColumnFilters(entry);
    }
    updateTableCount(entry);
  }

  function matchesAnyFilter(label, activeValues) {
    if (!label) return false;
    var lbl = String(label).toLowerCase();
    for (var j = 0; j < activeValues.length; j++) {
      if (valueMatchesFilter(lbl, activeValues[j])) return true;
    }
    return false;
  }

  function updateTableCount(entry) {
    var visibleCount = 0;
    entry.tbody.querySelectorAll('tr').forEach(function(r) {
      if (r.style.display !== 'none') visibleCount++;
    });
    if (entry.countEl) entry.countEl.textContent = entry.title + ' (' + visibleCount + ' records)';
  }

  // === RENDER CHART ===
  function renderChart(container, config, sectionId) {
    var type = config.type;

    // Delegate to custom renderers for non-Chart.js types
    if (type === 'heatmap') { renderHeatmap(container, config, sectionId); return; }
    if (type === 'funnel') { renderFunnel(container, config, sectionId); return; }
    if (type === 'waterfall') { renderWaterfall(container, config, sectionId); return; }
    if (type === 'gantt') { renderGantt(container, config, sectionId); return; }

    var card = el('div', { className: 'chart-card' });
    card.appendChild(el('h3', {}, config.title));
    var chartDiv = el('div', { className: 'chart-container' });
    var canvas = el('canvas', { id: 'chart-' + config.id });
    chartDiv.appendChild(canvas);
    card.appendChild(chartDiv);
    container.appendChild(card);

    if (typeof Chart === 'undefined') return;

    var opts = {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { position: 'bottom', labels: { padding: 16, usePointStyle: true, font: { size: 12 } } },
        tooltip: { backgroundColor: 'rgba(0,0,0,0.8)', padding: 12, cornerRadius: 8 }
      },
      scales: {}
    };

    if (type === 'horizontalBar') { type = 'bar'; opts.indexAxis = 'y'; }
    else if (config.indexAxis) { opts.indexAxis = config.indexAxis; }
    if (type === 'area') { type = 'line'; config.data.datasets.forEach(function(ds) { ds.fill = true; }); }

    if (type === 'treemap' && typeof Chart !== 'undefined' && !Chart.controllers.treemap) {
      // Treemap plugin not loaded — fallback to bar
      type = 'bar';
    }

    if (type === 'bar' || type === 'line') {
      opts.scales = {
        x: { grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } },
        y: { grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } }
      };
    }

    config.data.datasets.forEach(function(ds) {
      if (ds.borderWidth === undefined) ds.borderWidth = 2;
      if (ds.borderRadius === undefined && type === 'bar') ds.borderRadius = 6;
      if (ds.tension === undefined && type === 'line') ds.tension = 0.3;
    });

    var chartInstance = new Chart(canvas.getContext('2d'), {
      type: type,
      data: JSON.parse(JSON.stringify(config.data)),
      options: opts
    });

    var originalData = JSON.parse(JSON.stringify(config.data));

    if (sectionId) {
      if (!sectionCharts[sectionId]) sectionCharts[sectionId] = [];
      sectionCharts[sectionId].push({ id: config.id, config: config, instance: chartInstance, card: card, originalData: originalData });
    }

    canvas.onclick = function(evt) {
      var points = chartInstance.getElementsAtEventForMode(evt, 'nearest', { intersect: true }, true);
      if (points.length) {
        var idx = points[0].index;
        var dsIdx = points[0].datasetIndex;
        var label = config.data.labels[idx];
        var value = config.data.datasets[dsIdx].data[idx];
        var dsLabel = config.data.datasets[dsIdx].label;

        if (sectionId && sectionCharts[sectionId] && sectionCharts[sectionId].length > 1) {
          applyCrossFilter(sectionId, label, config.id);
        }

        showDrillDown(config.title + ' \\u2014 ' + label, [
          { label: 'Category', value: String(label) },
          { label: 'Dataset', value: dsLabel },
          { label: 'Value', value: typeof value === 'number' ? value.toLocaleString() : JSON.stringify(value) },
          { label: 'Index', value: '#' + (idx + 1) }
        ]);
      }
    };
  }

  // === HEATMAP RENDERER (pure HTML/CSS) ===
  function renderHeatmap(container, config, sectionId) {
    var card = el('div', { className: 'chart-card heatmap-card' });
    card.appendChild(el('h3', {}, config.title));

    var labels = config.data.labels || [];
    var datasets = config.data.datasets || [];
    var primary = getComputedStyle(document.documentElement).getPropertyValue('--md-primary').trim() || '#6750A4';

    var allValues = [];
    datasets.forEach(function(ds) { (ds.data || []).forEach(function(v) { if (typeof v === 'number') allValues.push(v); }); });
    var minVal = Math.min.apply(null, allValues);
    var maxVal = Math.max.apply(null, allValues);
    var range = maxVal - minVal || 1;

    var grid = el('div', { className: 'heatmap-grid' });
    var headerRow = el('div', { className: 'heatmap-row heatmap-header' });
    headerRow.appendChild(el('div', { className: 'heatmap-cell heatmap-label' }, ''));
    labels.forEach(function(lbl) { headerRow.appendChild(el('div', { className: 'heatmap-cell heatmap-col-label' }, lbl)); });
    grid.appendChild(headerRow);

    datasets.forEach(function(ds) {
      var row = el('div', { className: 'heatmap-row', 'data-label': ds.label });
      row.appendChild(el('div', { className: 'heatmap-cell heatmap-label' }, ds.label));
      (ds.data || []).forEach(function(val, i) {
        var intensity = typeof val === 'number' ? (val - minVal) / range : 0;
        var cell = el('div', { className: 'heatmap-cell heatmap-value', 'data-col-label': labels[i] || '' });
        cell.style.backgroundColor = addAlpha(primary, 0.1 + intensity * 0.8);
        cell.style.color = intensity > 0.5 ? '#fff' : 'inherit';
        cell.textContent = typeof val === 'number' ? val.toLocaleString() : String(val);
        cell.title = ds.label + ' / ' + (labels[i] || '') + ': ' + val;
        row.appendChild(cell);
      });
      grid.appendChild(row);
    });

    card.appendChild(grid);

    var legend = el('div', { className: 'heatmap-legend' });
    legend.appendChild(el('span', {}, 'Low'));
    for (var i = 0; i <= 4; i++) {
      var swatch = el('div', { className: 'heatmap-swatch' });
      swatch.style.backgroundColor = addAlpha(primary, 0.1 + (i / 4) * 0.8);
      legend.appendChild(swatch);
    }
    legend.appendChild(el('span', {}, 'High'));
    card.appendChild(legend);
    container.appendChild(card);

    // Register for global filtering
    if (sectionId) {
      if (!sectionCharts[sectionId]) sectionCharts[sectionId] = [];
      var allLabels = labels.concat(datasets.map(function(ds) { return ds.label; }));
      sectionCharts[sectionId].push({
        id: config.id, config: config, instance: null, card: card,
        originalData: config.data, labels: allLabels,
        applyFilter: function(activeFilters) {
          var dataRows = grid.querySelectorAll('.heatmap-row:not(.heatmap-header)');
          var colHeaders = grid.querySelectorAll('.heatmap-header .heatmap-col-label');
          var activeValues = activeFilters.map(function(f) { return f.value; });

          // Filter rows
          var anyRowMatch = false;
          dataRows.forEach(function(row) {
            var rowLabel = row.getAttribute('data-label') || '';
            var matches = activeValues.some(function(v) { return valueMatchesFilter(rowLabel, v); });
            if (matches) { row.style.display = ''; anyRowMatch = true; }
            else { row.style.display = 'none'; }
          });
          // If no rows matched, show all (filter not applicable to row dimension)
          if (!anyRowMatch) {
            dataRows.forEach(function(row) { row.style.display = ''; });
          }

          // Filter columns
          var colMatchMap = {};
          var anyColMatch = false;
          labels.forEach(function(lbl, i) {
            var matches = activeValues.some(function(v) { return valueMatchesFilter(lbl, v); });
            colMatchMap[i] = matches;
            if (matches) anyColMatch = true;
          });
          if (anyColMatch) {
            dataRows.forEach(function(row) {
              var cells = row.querySelectorAll('.heatmap-value');
              cells.forEach(function(cell, i) {
                cell.style.display = colMatchMap[i] ? '' : 'none';
              });
            });
            colHeaders.forEach(function(ch, i) { ch.style.display = colMatchMap[i] ? '' : 'none'; });
          } else {
            // No col match — show all columns
            dataRows.forEach(function(row) {
              row.querySelectorAll('.heatmap-value').forEach(function(c) { c.style.display = ''; });
            });
            colHeaders.forEach(function(ch) { ch.style.display = ''; });
          }
        },
        resetFilter: function() {
          grid.querySelectorAll('.heatmap-row').forEach(function(row) { row.style.display = ''; });
          grid.querySelectorAll('.heatmap-value, .heatmap-col-label').forEach(function(c) { c.style.display = ''; });
        }
      });
    }
  }

  // === FUNNEL RENDERER (pure CSS) ===
  function renderFunnel(container, config, sectionId) {
    var card = el('div', { className: 'chart-card funnel-card' });
    card.appendChild(el('h3', {}, config.title));

    var labels = config.data.labels || [];
    var values = (config.data.datasets[0] || {}).data || [];
    var maxVal = Math.max.apply(null, values) || 1;

    var funnel = el('div', { className: 'funnel-container' });
    labels.forEach(function(lbl, i) {
      var pct = (values[i] || 0) / maxVal * 100;
      var step = el('div', { className: 'funnel-step', 'data-label': lbl });
      var bar = el('div', { className: 'funnel-bar' });
      bar.style.width = pct + '%';
      var hue = (i * 35 + 200) % 360;
      bar.style.backgroundColor = 'hsl(' + hue + ', 55%, 55%)';
      var text = el('span', { className: 'funnel-text' }, lbl + ': ' + (values[i] || 0).toLocaleString());
      bar.appendChild(text);
      step.appendChild(bar);
      funnel.appendChild(step);
    });
    card.appendChild(funnel);
    container.appendChild(card);

    // Register for global filtering
    if (sectionId) {
      if (!sectionCharts[sectionId]) sectionCharts[sectionId] = [];
      sectionCharts[sectionId].push({
        id: config.id, config: config, instance: null, card: card,
        originalData: config.data, labels: labels,
        applyFilter: function(activeFilters) {
          var activeValues = activeFilters.map(function(f) { return f.value; });
          var steps = funnel.querySelectorAll('.funnel-step');
          var anyMatch = false;
          steps.forEach(function(step) {
            var lbl = step.getAttribute('data-label') || '';
            var matches = activeValues.some(function(v) { return valueMatchesFilter(lbl, v); });
            step.style.display = matches ? '' : 'none';
            if (matches) anyMatch = true;
          });
          // If no matches, show all (filter not applicable)
          if (!anyMatch) {
            steps.forEach(function(step) { step.style.display = ''; });
          }
        },
        resetFilter: function() {
          funnel.querySelectorAll('.funnel-step').forEach(function(s) { s.style.display = ''; });
        }
      });
    }
  }

  // === WATERFALL RENDERER (Chart.js floating bars) ===
  function renderWaterfall(container, config, sectionId) {
    var card = el('div', { className: 'chart-card' });
    card.appendChild(el('h3', {}, config.title));
    var chartDiv = el('div', { className: 'chart-container' });
    var canvas = el('canvas', { id: 'chart-' + config.id });
    chartDiv.appendChild(canvas);
    card.appendChild(chartDiv);
    container.appendChild(card);

    if (typeof Chart === 'undefined') return;

    var labels = config.data.labels || [];
    var rawData = (config.data.datasets[0] || {}).data || [];
    var primary = getComputedStyle(document.documentElement).getPropertyValue('--md-primary').trim() || '#6750A4';
    var errorColor = getComputedStyle(document.documentElement).getPropertyValue('--md-error').trim() || '#B3261E';

    // Calculate running totals for floating bars
    var floatingData = [];
    var colors = [];
    var running = 0;
    rawData.forEach(function(val, i) {
      var start = running;
      running += val;
      floatingData.push([Math.min(start, running), Math.max(start, running)]);
      colors.push(val >= 0 ? primary : errorColor);
    });

    var wfChartData = {
      labels: labels,
      datasets: [{
        label: (config.data.datasets[0] || {}).label || 'Value',
        data: floatingData,
        backgroundColor: colors,
        borderRadius: 4,
        borderSkipped: false
      }]
    };
    var wfInstance = new Chart(canvas.getContext('2d'), {
      type: 'bar',
      data: JSON.parse(JSON.stringify(wfChartData)),
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false }, tooltip: { backgroundColor: 'rgba(0,0,0,0.8)', padding: 12, cornerRadius: 8 } },
        scales: {
          x: { grid: { display: false }, ticks: { font: { size: 11 } } },
          y: { grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } }
        }
      }
    });
    // Register for global filtering
    if (sectionId) {
      if (!sectionCharts[sectionId]) sectionCharts[sectionId] = [];
      sectionCharts[sectionId].push({ id: config.id, config: config, instance: wfInstance, card: card, originalData: wfChartData });
    }
  }

  // === GANTT RENDERER (horizontal stacked bars) ===
  function renderGantt(container, config, sectionId) {
    var card = el('div', { className: 'chart-card' });
    card.appendChild(el('h3', {}, config.title));
    var chartDiv = el('div', { className: 'chart-container gantt-container' });
    var canvas = el('canvas', { id: 'chart-' + config.id });
    chartDiv.appendChild(canvas);
    card.appendChild(chartDiv);
    container.appendChild(card);

    if (typeof Chart === 'undefined') return;

    var primary = getComputedStyle(document.documentElement).getPropertyValue('--md-primary').trim() || '#6750A4';

    var opts = {
      responsive: true,
      maintainAspectRatio: false,
      indexAxis: 'y',
      plugins: {
        legend: { position: 'bottom', labels: { padding: 16, usePointStyle: true, font: { size: 12 } } },
        tooltip: { backgroundColor: 'rgba(0,0,0,0.8)', padding: 12, cornerRadius: 8 }
      },
      scales: {
        x: { stacked: true, grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } },
        y: { stacked: true, grid: { display: false }, ticks: { font: { size: 11 } } }
      }
    };

    config.data.datasets.forEach(function(ds) {
      if (ds.borderWidth === undefined) ds.borderWidth = 1;
      if (ds.borderRadius === undefined) ds.borderRadius = 4;
    });

    var ganttData = JSON.parse(JSON.stringify(config.data));
    var ganttInstance = new Chart(canvas.getContext('2d'), {
      type: 'bar',
      data: ganttData,
      options: opts
    });
    // Register for global filtering
    if (sectionId) {
      if (!sectionCharts[sectionId]) sectionCharts[sectionId] = [];
      sectionCharts[sectionId].push({ id: config.id, config: config, instance: ganttInstance, card: card, originalData: JSON.parse(JSON.stringify(config.data)) });
    }
  }

  // === RENDER TABLE ===
  function renderTable(container, config, sectionId) {
    var rows = config.rows || (config.generateRows ? generateTableRows(config.generateRows) : []);
    var card = el('div', { className: 'table-card' });
    var countEl = el('h3', {}, config.title + ' (' + rows.length + ' records)');
    card.appendChild(countEl);

    var scroll = el('div', { className: 'table-scroll' });
    var table = el('table', {});

    var thead = el('thead', {});
    var headerRow = el('tr', {});
    config.columns.forEach(function(col, colIdx) {
      var th = el('th', {});
      th.appendChild(document.createTextNode(col.label + ' '));
      // Per-column filter icon
      var filterBtn = el('button', { className: 'th-filter-btn', title: 'Filter ' + col.label });
      filterBtn.innerHTML = '&#9662;';
      filterBtn.addEventListener('click', function(e) {
        e.stopPropagation();
        toggleColumnFilter(card, tbody, config.columns, colIdx, th);
      });
      th.appendChild(filterBtn);
      headerRow.appendChild(th);
    });
    thead.appendChild(headerRow);
    table.appendChild(thead);

    var tbody = el('tbody', {});
    rows.forEach(function(row, idx) {
      var tr = el('tr', {});
      var labelParts = [];
      config.columns.forEach(function(col) {
        var val = String(row[col.key] != null ? row[col.key] : '');
        tr.appendChild(el('td', {}, val));
        labelParts.push(val);
      });
      tr.setAttribute('data-labels', labelParts.join('|'));
      tr.onclick = function() {
        var fields = config.columns.map(function(col) {
          return { label: col.label, value: String(row[col.key] != null ? row[col.key] : '') };
        });
        showDrillDown(config.title + ' \\u2014 Record #' + (idx + 1), fields);
      };
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    scroll.appendChild(table);
    card.appendChild(scroll);
    container.appendChild(card);

    // Register table for global filtering
    sectionTables.push({ tbody: tbody, columns: config.columns, title: config.title, countEl: countEl, sectionId: sectionId || null });
  }

  // === PER-COLUMN TABLE FILTER ===
  var activeColumnFilters = {};

  function toggleColumnFilter(card, tbody, columns, colIdx, thEl) {
    // Close any existing dropdown
    var existing = card.querySelector('.col-filter-dropdown');
    if (existing) { existing.remove(); return; }

    // Gather unique values for this column
    var uniqueVals = {};
    tbody.querySelectorAll('tr').forEach(function(row) {
      var cells = row.querySelectorAll('td');
      if (cells[colIdx]) {
        var v = cells[colIdx].textContent.trim();
        if (v) uniqueVals[v] = true;
      }
    });
    var values = Object.keys(uniqueVals).sort();

    var dropdown = el('div', { className: 'col-filter-dropdown' });
    // "All" option
    var allBtn = el('button', { className: 'col-filter-option active' }, '(All)');
    allBtn.addEventListener('click', function() {
      delete activeColumnFilters[colIdx];
      applyColumnFilters(tbody, columns);
      dropdown.remove();
    });
    dropdown.appendChild(allBtn);

    values.forEach(function(val) {
      var btn = el('button', { className: 'col-filter-option' }, val);
      btn.addEventListener('click', function() {
        activeColumnFilters[colIdx] = val;
        applyColumnFilters(tbody, columns);
        dropdown.remove();
      });
      dropdown.appendChild(btn);
    });

    thEl.style.position = 'relative';
    thEl.appendChild(dropdown);

    // Close on outside click
    setTimeout(function() {
      document.addEventListener('click', function closeDD(e) {
        if (!dropdown.contains(e.target)) { dropdown.remove(); document.removeEventListener('click', closeDD); }
      });
    }, 0);
  }

  function applyColumnFilters(tbody, columns) {
    tbody.querySelectorAll('tr').forEach(function(row) {
      var cells = row.querySelectorAll('td');
      var visible = true;
      for (var ci in activeColumnFilters) {
        if (activeColumnFilters.hasOwnProperty(ci)) {
          var cellVal = cells[ci] ? cells[ci].textContent.trim() : '';
          if (cellVal !== activeColumnFilters[ci]) { visible = false; break; }
        }
      }
      row.style.display = visible ? '' : 'none';
    });
  }

  // === DRILL-DOWN ===
  var MOCK_NOTES = [
    'Trending above forecast \\u2014 monitor for sustained momentum.',
    'Review scheduled for next quarter. Stakeholder alignment in progress.',
    'Key dependency on vendor timeline. Risk mitigation plan active.',
    'Performance exceeds benchmark by 12%. Recommend expanding scope.',
    'Under review \\u2014 awaiting executive sign-off on budget allocation.',
    'Strong quarter-over-quarter improvement. Team capacity at 85%.',
    'Flagged for deep-dive in upcoming board presentation.',
    'Cross-functional initiative \\u2014 coordinating with 3 departments.',
    'Pilot phase complete. Results support full rollout recommendation.',
    'Budget reallocation pending. Impact analysis submitted to finance.'
  ];

  function showDrillDown(title, fields) {
    var overlay = document.getElementById('drilldown-overlay');
    overlay.innerHTML = '';
    overlay.classList.remove('hidden');

    var modal = el('div', { className: 'drilldown-modal' });
    var header = el('div', { className: 'drilldown-header' });
    header.appendChild(el('h3', {}, title));
    header.appendChild(el('button', { className: 'drilldown-close', onclick: closeDrillDown }, '\\u00D7'));
    modal.appendChild(header);

    var body = el('div', { className: 'drilldown-body' });
    fields.forEach(function(f) {
      var field = el('div', { className: 'drilldown-field' });
      field.appendChild(el('span', { className: 'drilldown-label' }, f.label));
      field.appendChild(el('span', { className: 'drilldown-value' }, f.value));
      body.appendChild(field);
    });

    var noteIdx = Math.abs(title.split('').reduce(function(a, c) { return a + c.charCodeAt(0); }, 0)) % MOCK_NOTES.length;
    var notesSection = el('div', { className: 'drilldown-notes' });
    notesSection.appendChild(el('h4', { className: 'drilldown-notes-title' }, 'Notes & Context'));
    notesSection.appendChild(el('p', { className: 'drilldown-notes-text' }, MOCK_NOTES[noteIdx]));
    notesSection.appendChild(el('p', { className: 'drilldown-notes-text' }, MOCK_NOTES[(noteIdx + 3) % MOCK_NOTES.length]));
    body.appendChild(notesSection);

    modal.appendChild(body);
    overlay.appendChild(modal);

    requestAnimationFrame(function() { overlay.classList.add('visible'); });
    overlay.onclick = function(e) { if (e.target === overlay) closeDrillDown(); };
  }

  function closeDrillDown() {
    var overlay = document.getElementById('drilldown-overlay');
    overlay.classList.remove('visible');
    setTimeout(function() { overlay.classList.add('hidden'); overlay.innerHTML = ''; }, 300);
  }

  // === AGENTIC WORKFORCE ===
  function renderAgenticWorkforce(agents, sectionEl) {
    if (!agents || !agents.length) return;
    var banner = el('div', { className: 'coming-soon-banner' });
    banner.innerHTML = '<h2>\\uD83D\\uDEA7 Agentic Workforce \\u2014 Coming Soon</h2><p>AI-powered agents are being developed to augment your team across departments.</p>';
    sectionEl.appendChild(banner);

    var card = el('div', { className: 'table-card agentic-table' });
    card.appendChild(el('h3', {}, 'Planned AI Agents'));

    var scroll = el('div', { className: 'table-scroll' });
    var table = el('table', {});
    var thead = el('thead', {});
    var hr = el('tr', {});
    hr.appendChild(el('th', {}, 'Agent Name'));
    hr.appendChild(el('th', {}, 'Core Functionality'));
    hr.appendChild(el('th', {}, 'Primary Interfacing Teams'));
    thead.appendChild(hr);
    table.appendChild(thead);

    var tbody = el('tbody', {});
    agents.forEach(function(agent) {
      var tr = el('tr', {});
      tr.appendChild(el('td', { innerHTML: '<strong>' + agent.name + '</strong>' }));
      tr.appendChild(el('td', {}, agent.coreFunctionality));
      tr.appendChild(el('td', {}, agent.interfacingTeams));
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    scroll.appendChild(table);
    card.appendChild(scroll);
    sectionEl.appendChild(card);
  }

  // === CFO SCENARIOS ===
  var CFO_CHART_TYPES = ['line', 'bar', 'doughnut', 'radar'];

  function renderCFOScenarios(scenarios, sectionEl) {
    if (!scenarios || !scenarios.length) return;

    scenarios.forEach(function(scenario, sIdx) {
      var card = el('div', { className: 'cfo-card' });
      card.appendChild(el('h3', {}, scenario.title));
      card.appendChild(el('p', { className: 'cfo-desc' }, scenario.description));

      var sliderValues = {};
      var controlsDiv = el('div', { className: 'cfo-controls' });

      scenario.sliders.forEach(function(slider, sliderIdx) {
        sliderValues[slider.id] = slider['default'];

        var controlType = slider.controlType || (sliderIdx % 3 === 1 ? 'toggle' : (sliderIdx % 3 === 2 ? 'segmented' : 'slider'));

        if (controlType === 'toggle' && slider.options && slider.options.length === 2) {
          var group = el('div', { className: 'toggle-group' });
          var labelSpan = el('span', { className: 'toggle-label' }, slider.label);
          group.appendChild(labelSpan);

          var toggleWrap = el('div', { className: 'toggle-wrap' });
          slider.options.forEach(function(opt, oi) {
            var btn = el('button', {
              className: 'toggle-btn' + (oi === 0 ? ' active' : ''),
              'data-value': String(opt.value)
            }, opt.label);
            btn.addEventListener('click', function() {
              toggleWrap.querySelectorAll('.toggle-btn').forEach(function(b) { b.classList.remove('active'); });
              this.classList.add('active');
              sliderValues[slider.id] = parseFloat(this.getAttribute('data-value'));
              updateCFOChart(scenario, sliderValues, chartRef);
            });
            toggleWrap.appendChild(btn);
          });
          group.appendChild(toggleWrap);
          controlsDiv.appendChild(group);
        } else if (controlType === 'segmented' && slider.options && slider.options.length >= 3) {
          var group = el('div', { className: 'segmented-group' });
          group.appendChild(el('span', { className: 'toggle-label' }, slider.label));
          var segWrap = el('div', { className: 'segmented-wrap' });
          slider.options.forEach(function(opt, oi) {
            var btn = el('button', {
              className: 'segmented-btn' + (oi === 0 ? ' active' : ''),
              'data-value': String(opt.value)
            }, opt.label);
            btn.addEventListener('click', function() {
              segWrap.querySelectorAll('.segmented-btn').forEach(function(b) { b.classList.remove('active'); });
              this.classList.add('active');
              sliderValues[slider.id] = parseFloat(this.getAttribute('data-value'));
              updateCFOChart(scenario, sliderValues, chartRef);
            });
            segWrap.appendChild(btn);
          });
          group.appendChild(segWrap);
          controlsDiv.appendChild(group);
        } else {
          var group = el('div', { className: 'slider-group' });
          var labelDiv = el('div', { className: 'slider-label' });
          labelDiv.appendChild(el('span', {}, slider.label));
          var valueSpan = el('span', {}, slider['default'] + slider.unit);
          labelDiv.appendChild(valueSpan);
          group.appendChild(labelDiv);

          var input = document.createElement('input');
          input.type = 'range';
          input.min = slider.min;
          input.max = slider.max;
          input.step = slider.step;
          input.value = slider['default'];

          input.addEventListener('input', function() {
            sliderValues[slider.id] = parseFloat(this.value);
            valueSpan.textContent = this.value + slider.unit;
            updateCFOChart(scenario, sliderValues, chartRef);
          });

          group.appendChild(input);
          controlsDiv.appendChild(group);
        }
      });

      card.appendChild(controlsDiv);

      var chartType = scenario.chartType || CFO_CHART_TYPES[sIdx % CFO_CHART_TYPES.length];
      var isRadial = (chartType === 'doughnut' || chartType === 'radar');

      var chartDiv = el('div', { className: 'cfo-chart-container' });
      var canvas = el('canvas', { id: 'cfo-chart-' + scenario.id });
      chartDiv.appendChild(canvas);
      card.appendChild(chartDiv);
      sectionEl.appendChild(card);

      var chartRef = { instance: null };
      if (typeof Chart !== 'undefined') {
        var primaryColor = getComputedStyle(document.documentElement).getPropertyValue('--md-primary').trim() || '#6750A4';
        var secondaryColor = getComputedStyle(document.documentElement).getPropertyValue('--md-secondary').trim() || '#625B71';

        var cfoData = calculateCFO(scenario, sliderValues);
        var datasetConfig;
        if (chartType === 'doughnut') {
          datasetConfig = {
            label: scenario.metricLabel || 'Projected Revenue',
            data: cfoData,
            backgroundColor: cfoData.map(function(_, i) {
              var hue = (i * 60 + 200) % 360;
              return 'hsl(' + hue + ', 55%, 55%)';
            }),
            borderWidth: 2,
            borderColor: '#fff'
          };
        } else if (chartType === 'radar') {
          datasetConfig = {
            label: scenario.metricLabel || 'Projected Revenue',
            data: cfoData,
            borderColor: primaryColor,
            backgroundColor: primaryColor + '33',
            pointBackgroundColor: primaryColor,
            borderWidth: 2,
            fill: true
          };
        } else if (chartType === 'bar') {
          datasetConfig = {
            label: scenario.metricLabel || 'Projected Revenue',
            data: cfoData,
            backgroundColor: primaryColor + '99',
            borderColor: primaryColor,
            borderWidth: 1,
            borderRadius: 6
          };
        } else {
          datasetConfig = {
            label: scenario.metricLabel || 'Projected Revenue',
            data: cfoData,
            borderColor: primaryColor,
            backgroundColor: primaryColor + '33',
            fill: true,
            tension: 0.3,
            borderWidth: 2
          };
        }

        var chartOpts = {
          responsive: true,
          maintainAspectRatio: false,
          plugins: { legend: { display: true, position: 'bottom' } }
        };
        if (!isRadial) {
          chartOpts.scales = {
            y: {
              beginAtZero: false,
              grid: { color: 'rgba(0,0,0,0.06)' },
              ticks: {
                callback: function(value) {
                  if (scenario.currencyFormat !== false) {
                    if (Math.abs(value) >= 1000000) return '$' + (value / 1000000).toFixed(1) + 'M';
                    if (Math.abs(value) >= 1000) return '$' + (value / 1000).toFixed(0) + 'K';
                    return '$' + value;
                  }
                  return value;
                }
              }
            },
            x: { grid: { color: 'rgba(0,0,0,0.06)' } }
          };
        }

        chartRef.instance = new Chart(canvas.getContext('2d'), {
          type: chartType,
          data: {
            labels: scenario.quarters,
            datasets: [datasetConfig]
          },
          options: chartOpts
        });
      }
    });
  }

  function calculateCFO(scenario, values) {
    var base = scenario.baseline || {};
    var revenue = base.revenue || 1000000;
    var quarters = scenario.quarters || ['Q1','Q2','Q3'];
    var result = [];

    if (scenario.type === 'pricing') {
      var priceChange = (values.priceChange || 0) / 100;
      var elasticity = values.elasticity || 1.0;
      var growth = (values.growthRate || 0) / 100;
      for (var i = 0; i < quarters.length; i++) {
        var volumeImpact = 1 - (priceChange * elasticity);
        var growthFactor = Math.pow(1 + growth, i + 1);
        result.push(Math.round(revenue * (1 + priceChange) * volumeImpact * growthFactor));
      }
    } else if (scenario.type === 'headcount') {
      var hires = values.newHires || 0;
      var rampMonths = values.rampTime || 3;
      var quota = values.quota || 500000;
      for (var i = 0; i < quarters.length; i++) {
        var monthsIn = (i + 1) * 3;
        var effectiveReps = Math.min(hires, hires * (monthsIn / rampMonths));
        result.push(Math.round(revenue + effectiveReps * quota * (monthsIn / (rampMonths * 2))));
      }
    } else if (scenario.type === 'expansion') {
      var tam = values.tam || 10000000;
      var penetration = (values.penetration || 3) / 100;
      var investment = values.investment || 500000;
      for (var i = 0; i < quarters.length; i++) {
        var qRevenue = tam * penetration * ((i + 1) / quarters.length);
        result.push(Math.round(revenue + qRevenue - (investment / quarters.length)));
      }
    } else {
      for (var i = 0; i < quarters.length; i++) {
        result.push(Math.round(revenue * (1 + (i + 1) * 0.05)));
      }
    }

    return result;
  }

  function updateCFOChart(scenario, values, chartRef) {
    if (!chartRef.instance) return;
    chartRef.instance.data.datasets[0].data = calculateCFO(scenario, values);
    chartRef.instance.update('none');
  }

  // === TOAST ===
  function showToast(message) {
    var container = document.getElementById('toast-container');
    var toast = el('div', { className: 'toast' }, message);
    container.appendChild(toast);
    setTimeout(function() { toast.classList.add('show'); }, 10);
    setTimeout(function() {
      toast.classList.remove('show');
      setTimeout(function() { toast.remove(); }, 300);
    }, 3000);
  }

  // === LAYOUT RENDERERS ===
  var LAYOUT_LIST = ['default','kpi-spotlight','split-panel','full-width-timeline','grid-cards','map-table'];

  function renderSectionWithLayout(section, sectionEl) {
    var layout = section.layout || 'default';

    var headerDiv = el('div', { className: 'section-header' });
    headerDiv.appendChild(el('h2', {}, section.title));
    headerDiv.appendChild(el('p', {}, section.description));
    sectionEl.appendChild(headerDiv);

    switch (layout) {
      case 'kpi-spotlight':
        renderLayoutKpiSpotlight(section, sectionEl);
        break;
      case 'split-panel':
        renderLayoutSplitPanel(section, sectionEl);
        break;
      case 'full-width-timeline':
        renderLayoutFullWidthTimeline(section, sectionEl);
        break;
      case 'grid-cards':
        renderLayoutGridCards(section, sectionEl);
        break;
      case 'map-table':
        renderLayoutMapTable(section, sectionEl);
        break;
      default:
        renderLayoutDefault(section, sectionEl);
        break;
    }
  }

  function renderLayoutDefault(section, sectionEl) {
    renderMetrics(sectionEl, section.metrics);
    if (section.charts && section.charts.length) {
      var chartsGrid = el('div', { className: 'charts-grid' });
      section.charts.forEach(function(c) { renderChart(chartsGrid, c, section.id); });
      sectionEl.appendChild(chartsGrid);
    }
    if (section.tables && section.tables.length) {
      section.tables.forEach(function(t) { renderTable(sectionEl, t, section.id); });
    }
  }

  function renderLayoutKpiSpotlight(section, sectionEl) {
    var metrics = section.metrics || [];
    if (metrics.length) {
      var spotlight = el('div', { className: 'kpi-spotlight-container' });
      // Hero metric
      var hero = el('div', { className: 'kpi-hero' });
      hero.appendChild(el('span', { className: 'metric-label' }, metrics[0].label));
      hero.appendChild(el('span', { className: 'kpi-hero-value' }, metrics[0].value));
      if (metrics[0].change) hero.appendChild(el('span', { className: 'metric-change ' + (metrics[0].trend || 'neutral') }, metrics[0].change));
      spotlight.appendChild(hero);

      // Secondary metrics
      if (metrics.length > 1) {
        var secondaryGrid = el('div', { className: 'kpi-secondary-grid' });
        for (var i = 1; i < metrics.length; i++) {
          var card = el('div', { className: 'metric-card' });
          card.appendChild(el('span', { className: 'metric-label' }, metrics[i].label));
          card.appendChild(el('span', { className: 'metric-value' }, metrics[i].value));
          if (metrics[i].change) card.appendChild(el('span', { className: 'metric-change ' + (metrics[i].trend || 'neutral') }, metrics[i].change));
          secondaryGrid.appendChild(card);
        }
        spotlight.appendChild(secondaryGrid);
      }
      sectionEl.appendChild(spotlight);
    }
    // Charts below
    if (section.charts && section.charts.length) {
      var chartsGrid = el('div', { className: 'charts-grid' });
      section.charts.forEach(function(c) { renderChart(chartsGrid, c, section.id); });
      sectionEl.appendChild(chartsGrid);
    }
  }

  function renderLayoutSplitPanel(section, sectionEl) {
    var panel = el('div', { className: 'split-panel' });
    // Left: large chart
    var left = el('div', { className: 'split-left' });
    if (section.charts && section.charts.length) {
      renderChart(left, section.charts[0], section.id);
    }
    panel.appendChild(left);

    // Right: metrics + mini chart
    var right = el('div', { className: 'split-right' });
    renderMetrics(right, section.metrics);
    if (section.charts && section.charts.length > 1) {
      renderChart(right, section.charts[1], section.id);
    }
    panel.appendChild(right);
    sectionEl.appendChild(panel);

    // Tables below
    if (section.tables && section.tables.length) {
      section.tables.forEach(function(t) { renderTable(sectionEl, t, section.id); });
    }
    // Remaining charts
    if (section.charts && section.charts.length > 2) {
      var extra = el('div', { className: 'charts-grid' });
      for (var i = 2; i < section.charts.length; i++) { renderChart(extra, section.charts[i], section.id); }
      sectionEl.appendChild(extra);
    }
  }

  function renderLayoutFullWidthTimeline(section, sectionEl) {
    renderMetrics(sectionEl, section.metrics);
    // First chart gets full width
    if (section.charts && section.charts.length) {
      var fullWidth = el('div', { className: 'full-width-chart' });
      renderChart(fullWidth, section.charts[0], section.id);
      sectionEl.appendChild(fullWidth);
    }
    // Remaining charts in grid
    if (section.charts && section.charts.length > 1) {
      var chartsGrid = el('div', { className: 'charts-grid' });
      for (var i = 1; i < section.charts.length; i++) { renderChart(chartsGrid, section.charts[i], section.id); }
      sectionEl.appendChild(chartsGrid);
    }
    if (section.tables && section.tables.length) {
      section.tables.forEach(function(t) { renderTable(sectionEl, t, section.id); });
    }
  }

  function renderLayoutGridCards(section, sectionEl) {
    var metrics = section.metrics || [];
    var charts = section.charts || [];
    var grid = el('div', { className: 'grid-cards-container' });

    // Pair metrics with mini charts
    metrics.forEach(function(m, i) {
      var card = el('div', { className: 'grid-card-item' });
      card.appendChild(el('span', { className: 'metric-label' }, m.label));
      card.appendChild(el('span', { className: 'metric-value' }, m.value));
      if (m.change) card.appendChild(el('span', { className: 'metric-change ' + (m.trend || 'neutral') }, m.change));
      // Embed a mini chart if available
      if (charts[i]) {
        var miniDiv = el('div', { className: 'grid-card-chart' });
        renderChart(miniDiv, charts[i], section.id);
        card.appendChild(miniDiv);
      }
      grid.appendChild(card);
    });
    sectionEl.appendChild(grid);

    // Remaining charts not paired with metrics
    if (charts.length > metrics.length) {
      var chartsGrid = el('div', { className: 'charts-grid' });
      for (var i = metrics.length; i < charts.length; i++) { renderChart(chartsGrid, charts[i], section.id); }
      sectionEl.appendChild(chartsGrid);
    }
    if (section.tables && section.tables.length) {
      section.tables.forEach(function(t) { renderTable(sectionEl, t, section.id); });
    }
  }

  function renderLayoutMapTable(section, sectionEl) {
    var panel = el('div', { className: 'map-table-panel' });
    // Left: heatmap or first chart
    var left = el('div', { className: 'map-table-left' });
    renderMetrics(left, section.metrics);
    if (section.charts && section.charts.length) {
      renderChart(left, section.charts[0], section.id);
    }
    panel.appendChild(left);

    // Right: table
    var right = el('div', { className: 'map-table-right' });
    if (section.tables && section.tables.length) {
      renderTable(right, section.tables[0], section.id);
    }
    panel.appendChild(right);
    sectionEl.appendChild(panel);

    // Extra charts/tables
    if (section.charts && section.charts.length > 1) {
      var extra = el('div', { className: 'charts-grid' });
      for (var i = 1; i < section.charts.length; i++) { renderChart(extra, section.charts[i], section.id); }
      sectionEl.appendChild(extra);
    }
    if (section.tables && section.tables.length > 1) {
      for (var i = 1; i < section.tables.length; i++) { renderTable(sectionEl, section.tables[i], section.id); }
    }
  }

  // === RENDER SECTIONS ===
  function renderSections(data) {
    var main = document.getElementById('main-content');

    data.navigation.forEach(function(nav) {
      var sectionEl = el('div', { className: 'dashboard-section', id: 'section-' + nav.id });
      main.appendChild(sectionEl);
    });

    // Enforce no adjacent duplicate layouts
    var prevLayout = null;
    data.sections.forEach(function(section) {
      if (section.layout && section.layout === prevLayout) {
        var idx = LAYOUT_LIST.indexOf(section.layout);
        section.layout = LAYOUT_LIST[(idx + 1) % LAYOUT_LIST.length];
      }
      prevLayout = section.layout || 'default';

      var sectionEl = document.getElementById('section-' + section.id);
      if (!sectionEl) return;
      renderSectionWithLayout(section, sectionEl);
    });

    // Agentic Workforce
    if (data.agenticWorkforce && data.agenticWorkforce.length) {
      var awSection = document.getElementById('section-agentic-workforce');
      if (awSection) {
        var awHeader = el('div', { className: 'section-header' });
        awHeader.appendChild(el('h2', {}, 'Agentic Workforce'));
        awSection.appendChild(awHeader);
        renderAgenticWorkforce(data.agenticWorkforce, awSection);
      }
    }

    // CFO View
    if (data.cfoScenarios && data.cfoScenarios.length) {
      var cfoSection = document.getElementById('section-cfo-view');
      if (cfoSection) {
        var cfoHeader = el('div', { className: 'section-header' });
        cfoHeader.appendChild(el('h2', {}, 'CFO What-If Scenarios'));
        cfoHeader.appendChild(el('p', {}, 'Adjust the sliders to model different business scenarios and see projected revenue impacts.'));
        cfoSection.appendChild(cfoHeader);
        renderCFOScenarios(data.cfoScenarios, cfoSection);
      }
    }
  }

  // === INIT ===
  document.addEventListener('DOMContentLoaded', function() {
    var data = window.__DASHBOARD_DATA__;
    if (!data) {
      document.body.innerHTML = '<div style="padding:40px;text-align:center;color:#666;">No dashboard data found.</div>';
      return;
    }

    applyBranding(data.branding);
    buildNavigation(data.navigation, data.meta);
    buildGlobalFilterBar(data.globalFilters);
    renderSections(data);

    // Show first section
    if (data.navigation.length) {
      showSection(data.navigation[0].id);
      var firstLink = document.querySelector('.nav-link');
      if (firstLink) firstLink.classList.add('active');
    }

    // Hamburger
    document.getElementById('hamburger-btn').addEventListener('click', function() {
      document.getElementById('sidebar').classList.toggle('collapsed');
    });

    // Escape key closes drill-down
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape') closeDrillDown();
    });

    showToast('Dashboard loaded successfully');
  });
})();
`;
}
