/**
 * Fixed JavaScript rendering engine for dashboards.
 * Reads window.__DASHBOARD_DATA__ (JSON) and builds the entire dashboard DOM.
 * This file is NEVER regenerated by the LLM — only data changes.
 */

export function getScriptsJs(): string {
  return `
(function() {
  'use strict';

  // === SEEDED PRNG (mulberry32) ===
  function mulberry32(a) {
    return function() {
      a |= 0; a = a + 0x6D2B79F5 | 0;
      var t = Math.imul(a ^ a >>> 15, 1 | a);
      t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
      return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
  }

  // === DATA GENERATORS ===
  var FIRST_NAMES = ['James','Mary','Robert','Patricia','John','Jennifer','Michael','Linda','David','Elizabeth','William','Barbara','Richard','Susan','Joseph','Jessica','Thomas','Sarah','Christopher','Karen','Charles','Lisa','Daniel','Nancy','Matthew','Betty','Anthony','Margaret','Mark','Sandra','Donald','Ashley','Steven','Kimberly','Andrew','Emily','Paul','Donna','Joshua','Michelle','Kenneth','Carol','Kevin','Amanda','Brian','Dorothy','George','Melissa','Timothy','Deborah'];
  var LAST_NAMES = ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson'];
  var REGIONS_DEFAULT = ['North America','EMEA','APAC','LATAM','ANZ','DACH','Nordics','UK','Southeast Asia','India'];

  var generators = {
    personName: function(rng) {
      return FIRST_NAMES[Math.floor(rng() * FIRST_NAMES.length)] + ' ' + LAST_NAMES[Math.floor(rng() * LAST_NAMES.length)];
    },
    company: function(rng, cfg) {
      var opts = cfg.options || ['Acme Corp','Globex Inc','Initech','Umbrella Co','Wayne Enterprises','Stark Industries','Oscorp','LexCorp'];
      return opts[Math.floor(rng() * opts.length)];
    },
    email: function(rng) {
      var name = FIRST_NAMES[Math.floor(rng() * FIRST_NAMES.length)].toLowerCase();
      var domains = ['gmail.com','company.com','enterprise.io','corp.net','mail.com'];
      return name + Math.floor(rng() * 999) + '@' + domains[Math.floor(rng() * domains.length)];
    },
    date: function(rng, cfg) {
      var days = cfg.maxDays || 365;
      var d = new Date();
      d.setDate(d.getDate() - Math.floor(rng() * days));
      return d.toISOString().split('T')[0];
    },
    futureDate: function(rng, cfg) {
      var days = cfg.maxDays || 180;
      var d = new Date();
      d.setDate(d.getDate() + Math.floor(rng() * days));
      return d.toISOString().split('T')[0];
    },
    currency: function(rng, cfg) {
      var min = cfg.min || 1000;
      var max = cfg.max || 100000;
      var val = Math.floor(min + rng() * (max - min));
      return '$' + val.toLocaleString('en-US');
    },
    integer: function(rng, cfg) {
      var min = cfg.min || 0;
      var max = cfg.max || 100;
      return Math.floor(min + rng() * (max - min));
    },
    percent: function(rng, cfg) {
      var min = cfg.min || 0;
      var max = cfg.max || 100;
      return (min + rng() * (max - min)).toFixed(1) + '%';
    },
    pick: function(rng, cfg) {
      var opts = cfg.options || ['Option A','Option B','Option C'];
      return opts[Math.floor(rng() * opts.length)];
    },
    status: function(rng, cfg) {
      var opts = cfg.options || ['Active','Pending','Closed','At Risk'];
      return opts[Math.floor(rng() * opts.length)];
    },
    region: function(rng, cfg) {
      var opts = cfg.options || REGIONS_DEFAULT;
      return opts[Math.floor(rng() * opts.length)];
    },
    product: function(rng, cfg) {
      var opts = cfg.options || ['Enterprise','Professional','Starter','Growth'];
      return opts[Math.floor(rng() * opts.length)];
    }
  };

  function generateTableRows(config) {
    var rng = mulberry32(config.seed || 42);
    var rows = [];
    for (var i = 0; i < config.count; i++) {
      var row = {};
      var fields = config.fields;
      for (var key in fields) {
        if (fields.hasOwnProperty(key)) {
          var gen = generators[fields[key].type];
          row[key] = gen ? gen(rng, fields[key]) : '';
        }
      }
      rows.push(row);
    }
    return rows;
  }

  // === DOM HELPERS ===
  function el(tag, attrs) {
    var elem = document.createElement(tag);
    if (attrs) {
      for (var k in attrs) {
        if (k === 'className') elem.className = attrs[k];
        else if (k === 'onclick') elem.onclick = attrs[k];
        else if (k === 'innerHTML') elem.innerHTML = attrs[k];
        else elem.setAttribute(k, attrs[k]);
      }
    }
    for (var i = 2; i < arguments.length; i++) {
      var child = arguments[i];
      if (!child) continue;
      if (typeof child === 'string') elem.appendChild(document.createTextNode(child));
      else elem.appendChild(child);
    }
    return elem;
  }

  // === BRANDING ===
  function applyBranding(b) {
    var s = document.documentElement.style;
    s.setProperty('--md-primary', b.primary || '#6750A4');
    s.setProperty('--md-on-primary', b.onPrimary || '#FFFFFF');
    s.setProperty('--md-primary-container', b.primaryContainer || '#EADDFF');
    s.setProperty('--md-on-primary-container', b.onPrimaryContainer || '#21005E');
    s.setProperty('--md-secondary', b.secondary || '#625B71');
    s.setProperty('--md-on-secondary', b.onSecondary || '#FFFFFF');
    s.setProperty('--md-surface', b.surface || '#FEF7FF');
    s.setProperty('--md-on-surface', b.onSurface || '#1D1B20');
    s.setProperty('--md-surface-variant', b.surfaceVariant || '#E7E0EC');
    s.setProperty('--md-outline', b.outline || '#79747E');
    s.setProperty('--md-error', b.error || '#B3261E');
    if (b.fontHeading) {
      s.setProperty('--font-heading', "'" + b.fontHeading + "', sans-serif");
      var link = document.createElement('link');
      link.href = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(b.fontHeading) + ':wght@400;500;600;700&display=swap';
      link.rel = 'stylesheet';
      document.head.appendChild(link);
    }
    if (b.fontBody && b.fontBody !== b.fontHeading) {
      s.setProperty('--font-body', "'" + b.fontBody + "', sans-serif");
      var link2 = document.createElement('link');
      link2.href = 'https://fonts.googleapis.com/css2?family=' + encodeURIComponent(b.fontBody) + ':wght@400;500&display=swap';
      link2.rel = 'stylesheet';
      document.head.appendChild(link2);
    }
  }

  // === LOGO ===
  function buildLogo(meta) {
    var container = document.getElementById('sidebar-logo');
    if (!container) return;

    var logoUrl = meta.logoUrl || '';
    var name = meta.companyName || 'Dashboard';

    if (logoUrl) {
      var img = document.createElement('img');
      img.src = logoUrl;
      img.alt = name + ' logo';
      img.crossOrigin = 'anonymous';
      img.onerror = function() {
        // Fallback to letter avatar
        img.remove();
        var letter = el('span', { className: 'logo-letter' }, name.charAt(0).toUpperCase());
        container.insertBefore(letter, container.firstChild);
      };
      container.appendChild(img);
    } else {
      container.appendChild(el('span', { className: 'logo-letter' }, name.charAt(0).toUpperCase()));
    }

    container.appendChild(el('span', { className: 'logo-name' }, name));
  }

  // === NAVIGATION ===
  function buildNavigation(nav, meta) {
    var header = document.getElementById('sidebar-header');
    header.appendChild(el('p', {}, meta.jobTitle || ''));

    var navEl = document.getElementById('sidebar-nav');
    nav.forEach(function(item) {
      var label = el('span', { className: 'nav-label' }, item.label);
      var link = el('a', { className: 'nav-link', 'data-section': item.id, 'data-tooltip': item.label, href: '#' },
        el('span', { className: 'material-icons-outlined' }, item.icon || 'dashboard'),
        label
      );
      link.addEventListener('click', function(e) {
        e.preventDefault();
        showSection(item.id);
        document.querySelectorAll('.nav-link').forEach(function(l) { l.classList.remove('active'); });
        this.classList.add('active');
        if (window.innerWidth <= 768) {
          document.getElementById('sidebar').classList.add('collapsed');
        }
      });
      navEl.appendChild(link);
    });

    document.getElementById('page-title').textContent = meta.companyName + ' \\u2014 ' + (meta.department || '') + ' Dashboard';
  }

  function showSection(id) {
    document.querySelectorAll('.dashboard-section').forEach(function(s) { s.style.display = 'none'; });
    var target = document.getElementById('section-' + id);
    if (target) target.style.display = 'block';
    setTimeout(function() {
      if (typeof Chart !== 'undefined') {
        Object.keys(Chart.instances).forEach(function(key) {
          Chart.instances[key].resize();
        });
      }
    }, 50);
  }

  // === RENDER METRICS ===
  function renderMetrics(container, metrics) {
    if (!metrics || !metrics.length) return;
    var grid = el('div', { className: 'metrics-grid' });
    metrics.forEach(function(m) {
      var card = el('div', { className: 'metric-card' });
      card.appendChild(el('span', { className: 'metric-label' }, m.label));
      card.appendChild(el('span', { className: 'metric-value' }, m.value));
      if (m.change) {
        card.appendChild(el('span', { className: 'metric-change ' + (m.trend || 'neutral') }, m.change));
      }
      grid.appendChild(card);
    });
    container.appendChild(grid);
  }

  // === RENDER CHART ===
  function renderChart(container, config) {
    var card = el('div', { className: 'chart-card' });
    card.appendChild(el('h3', {}, config.title));
    var chartDiv = el('div', { className: 'chart-container' });
    var canvas = el('canvas', { id: 'chart-' + config.id });
    chartDiv.appendChild(canvas);
    card.appendChild(chartDiv);
    container.appendChild(card);

    if (typeof Chart === 'undefined') return;

    var type = config.type;
    var opts = {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        legend: { position: 'bottom', labels: { padding: 16, usePointStyle: true, font: { size: 12 } } },
        tooltip: { backgroundColor: 'rgba(0,0,0,0.8)', padding: 12, cornerRadius: 8 }
      },
      scales: {}
    };

    if (type === 'horizontalBar') {
      type = 'bar';
      opts.indexAxis = 'y';
    } else if (config.indexAxis) {
      opts.indexAxis = config.indexAxis;
    }

    if (type === 'area') {
      type = 'line';
      config.data.datasets.forEach(function(ds) { ds.fill = true; });
    }

    if (type === 'bar' || type === 'line') {
      opts.scales = {
        x: { grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } },
        y: { grid: { color: 'rgba(0,0,0,0.06)' }, ticks: { font: { size: 11 } } }
      };
    }

    config.data.datasets.forEach(function(ds) {
      if (ds.borderWidth === undefined) ds.borderWidth = 2;
      if (ds.borderRadius === undefined && type === 'bar') ds.borderRadius = 6;
      if (ds.tension === undefined && type === 'line') ds.tension = 0.3;
    });

    var chartInstance = new Chart(canvas.getContext('2d'), {
      type: type,
      data: JSON.parse(JSON.stringify(config.data)),
      options: opts
    });

    // Drill-down on chart click
    canvas.onclick = function(evt) {
      var points = chartInstance.getElementsAtEventForMode(evt, 'nearest', { intersect: true }, true);
      if (points.length) {
        var idx = points[0].index;
        var dsIdx = points[0].datasetIndex;
        var label = config.data.labels[idx];
        var value = config.data.datasets[dsIdx].data[idx];
        var dsLabel = config.data.datasets[dsIdx].label;
        showDrillDown(config.title + ' \\u2014 ' + label, [
          { label: 'Category', value: String(label) },
          { label: 'Dataset', value: dsLabel },
          { label: 'Value', value: typeof value === 'number' ? value.toLocaleString() : JSON.stringify(value) },
          { label: 'Index', value: '#' + (idx + 1) }
        ]);
      }
    };
  }

  // === RENDER TABLE ===
  function renderTable(container, config) {
    var rows = config.rows || (config.generateRows ? generateTableRows(config.generateRows) : []);
    var card = el('div', { className: 'table-card' });
    card.appendChild(el('h3', {}, config.title + ' (' + rows.length + ' records)'));

    var scroll = el('div', { className: 'table-scroll' });
    var table = el('table', {});

    var thead = el('thead', {});
    var headerRow = el('tr', {});
    config.columns.forEach(function(col) {
      headerRow.appendChild(el('th', {}, col.label));
    });
    thead.appendChild(headerRow);
    table.appendChild(thead);

    var tbody = el('tbody', {});
    rows.forEach(function(row, idx) {
      var tr = el('tr', {});
      config.columns.forEach(function(col) {
        tr.appendChild(el('td', {}, String(row[col.key] != null ? row[col.key] : '')));
      });
      tr.onclick = function() {
        var fields = config.columns.map(function(col) {
          return { label: col.label, value: String(row[col.key] != null ? row[col.key] : '') };
        });
        showDrillDown(config.title + ' \\u2014 Record #' + (idx + 1), fields);
      };
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    scroll.appendChild(table);
    card.appendChild(scroll);
    container.appendChild(card);
  }

  // === DRILL-DOWN ===
  function showDrillDown(title, fields) {
    var overlay = document.getElementById('drilldown-overlay');
    overlay.innerHTML = '';
    overlay.classList.remove('hidden');

    var modal = el('div', { className: 'drilldown-modal' });
    var header = el('div', { className: 'drilldown-header' });
    header.appendChild(el('h3', {}, title));
    header.appendChild(el('button', { className: 'drilldown-close', onclick: closeDrillDown }, '\\u00D7'));
    modal.appendChild(header);

    var body = el('div', { className: 'drilldown-body' });
    fields.forEach(function(f) {
      var field = el('div', { className: 'drilldown-field' });
      field.appendChild(el('span', { className: 'drilldown-label' }, f.label));
      field.appendChild(el('span', { className: 'drilldown-value' }, f.value));
      body.appendChild(field);
    });
    modal.appendChild(body);
    overlay.appendChild(modal);

    requestAnimationFrame(function() { overlay.classList.add('visible'); });
    overlay.onclick = function(e) { if (e.target === overlay) closeDrillDown(); };
  }

  function closeDrillDown() {
    var overlay = document.getElementById('drilldown-overlay');
    overlay.classList.remove('visible');
    setTimeout(function() { overlay.classList.add('hidden'); overlay.innerHTML = ''; }, 300);
  }

  // === AGENTIC WORKFORCE ===
  function renderAgenticWorkforce(agents, sectionEl) {
    if (!agents || !agents.length) return;
    var banner = el('div', { className: 'coming-soon-banner' });
    banner.innerHTML = '<h2>\\uD83D\\uDEA7 Agentic Workforce \\u2014 Coming Soon</h2><p>AI-powered agents are being developed to augment your team across departments.</p>';
    sectionEl.appendChild(banner);

    var card = el('div', { className: 'table-card agentic-table' });
    card.appendChild(el('h3', {}, 'Planned AI Agents'));

    var scroll = el('div', { className: 'table-scroll' });
    var table = el('table', {});
    var thead = el('thead', {});
    var hr = el('tr', {});
    hr.appendChild(el('th', {}, 'Agent Name'));
    hr.appendChild(el('th', {}, 'Core Functionality'));
    hr.appendChild(el('th', {}, 'Primary Interfacing Teams'));
    thead.appendChild(hr);
    table.appendChild(thead);

    var tbody = el('tbody', {});
    agents.forEach(function(agent) {
      var tr = el('tr', {});
      tr.appendChild(el('td', { innerHTML: '<strong>' + agent.name + '</strong>' }));
      tr.appendChild(el('td', {}, agent.coreFunctionality));
      tr.appendChild(el('td', {}, agent.interfacingTeams));
      tbody.appendChild(tr);
    });
    table.appendChild(tbody);
    scroll.appendChild(table);
    card.appendChild(scroll);
    sectionEl.appendChild(card);
  }

  // === CFO SCENARIOS ===
  function renderCFOScenarios(scenarios, sectionEl) {
    if (!scenarios || !scenarios.length) return;

    scenarios.forEach(function(scenario) {
      var card = el('div', { className: 'cfo-card' });
      card.appendChild(el('h3', {}, scenario.title));
      card.appendChild(el('p', { className: 'cfo-desc' }, scenario.description));

      var sliderValues = {};
      var slidersDiv = el('div', {});

      scenario.sliders.forEach(function(slider) {
        sliderValues[slider.id] = slider['default'];

        var group = el('div', { className: 'slider-group' });
        var labelDiv = el('div', { className: 'slider-label' });
        labelDiv.appendChild(el('span', {}, slider.label));
        var valueSpan = el('span', {}, slider['default'] + slider.unit);
        labelDiv.appendChild(valueSpan);
        group.appendChild(labelDiv);

        var input = document.createElement('input');
        input.type = 'range';
        input.min = slider.min;
        input.max = slider.max;
        input.step = slider.step;
        input.value = slider['default'];

        input.addEventListener('input', function() {
          sliderValues[slider.id] = parseFloat(this.value);
          valueSpan.textContent = this.value + slider.unit;
          updateCFOChart(scenario, sliderValues, chartRef);
        });

        group.appendChild(input);
        slidersDiv.appendChild(group);
      });

      card.appendChild(slidersDiv);

      var chartDiv = el('div', { className: 'cfo-chart-container' });
      var canvas = el('canvas', { id: 'cfo-chart-' + scenario.id });
      chartDiv.appendChild(canvas);
      card.appendChild(chartDiv);
      sectionEl.appendChild(card);

      var chartRef = { instance: null };
      if (typeof Chart !== 'undefined') {
        var primaryColor = getComputedStyle(document.documentElement).getPropertyValue('--md-primary').trim() || '#6750A4';
        chartRef.instance = new Chart(canvas.getContext('2d'), {
          type: scenario.chartType || 'line',
          data: {
            labels: scenario.quarters,
            datasets: [{
              label: 'Projected Revenue',
              data: calculateCFO(scenario, sliderValues),
              borderColor: primaryColor,
              backgroundColor: primaryColor + '33',
              fill: true,
              tension: 0.3,
              borderWidth: 2
            }]
          },
          options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
              y: { beginAtZero: false, grid: { color: 'rgba(0,0,0,0.06)' } },
              x: { grid: { color: 'rgba(0,0,0,0.06)' } }
            },
            plugins: { legend: { display: true, position: 'bottom' } }
          }
        });
      }
    });
  }

  function calculateCFO(scenario, values) {
    var base = scenario.baseline || {};
    var revenue = base.revenue || 1000000;
    var quarters = scenario.quarters || ['Q1','Q2','Q3'];
    var result = [];

    if (scenario.type === 'pricing') {
      var priceChange = (values.priceChange || 0) / 100;
      var elasticity = values.elasticity || 1.0;
      var growth = (values.growthRate || 0) / 100;
      for (var i = 0; i < quarters.length; i++) {
        var volumeImpact = 1 - (priceChange * elasticity);
        var growthFactor = Math.pow(1 + growth, i + 1);
        result.push(Math.round(revenue * (1 + priceChange) * volumeImpact * growthFactor));
      }
    } else if (scenario.type === 'headcount') {
      var hires = values.newHires || 0;
      var rampMonths = values.rampTime || 3;
      var quota = values.quota || 500000;
      for (var i = 0; i < quarters.length; i++) {
        var monthsIn = (i + 1) * 3;
        var effectiveReps = Math.min(hires, hires * (monthsIn / rampMonths));
        result.push(Math.round(revenue + effectiveReps * quota * (monthsIn / (rampMonths * 2))));
      }
    } else if (scenario.type === 'expansion') {
      var tam = values.tam || 10000000;
      var penetration = (values.penetration || 3) / 100;
      var investment = values.investment || 500000;
      for (var i = 0; i < quarters.length; i++) {
        var qRevenue = tam * penetration * ((i + 1) / quarters.length);
        result.push(Math.round(revenue + qRevenue - (investment / quarters.length)));
      }
    } else {
      for (var i = 0; i < quarters.length; i++) {
        result.push(Math.round(revenue * (1 + (i + 1) * 0.05)));
      }
    }

    return result;
  }

  function updateCFOChart(scenario, values, chartRef) {
    if (!chartRef.instance) return;
    chartRef.instance.data.datasets[0].data = calculateCFO(scenario, values);
    chartRef.instance.update('none');
  }

  // === TOAST ===
  function showToast(message) {
    var container = document.getElementById('toast-container');
    var toast = el('div', { className: 'toast' }, message);
    container.appendChild(toast);
    setTimeout(function() { toast.classList.add('show'); }, 10);
    setTimeout(function() {
      toast.classList.remove('show');
      setTimeout(function() { toast.remove(); }, 300);
    }, 3000);
  }

  // === RENDER SECTIONS ===
  function renderSections(data) {
    var main = document.getElementById('main-content');

    // Create all section containers from navigation
    data.navigation.forEach(function(nav) {
      var sectionEl = el('div', { className: 'dashboard-section', id: 'section-' + nav.id });
      main.appendChild(sectionEl);
    });

    // Populate data sections
    data.sections.forEach(function(section) {
      var sectionEl = document.getElementById('section-' + section.id);
      if (!sectionEl) return;

      var headerDiv = el('div', { className: 'section-header' });
      headerDiv.appendChild(el('h2', {}, section.title));
      headerDiv.appendChild(el('p', {}, section.description));
      sectionEl.appendChild(headerDiv);

      renderMetrics(sectionEl, section.metrics);

      if (section.charts && section.charts.length) {
        var chartsGrid = el('div', { className: 'charts-grid' });
        section.charts.forEach(function(chartConfig) {
          renderChart(chartsGrid, chartConfig);
        });
        sectionEl.appendChild(chartsGrid);
      }

      if (section.tables && section.tables.length) {
        section.tables.forEach(function(tableConfig) {
          renderTable(sectionEl, tableConfig);
        });
      }
    });

    // Agentic Workforce
    if (data.agenticWorkforce && data.agenticWorkforce.length) {
      var awSection = document.getElementById('section-agentic-workforce');
      if (awSection) {
        var awHeader = el('div', { className: 'section-header' });
        awHeader.appendChild(el('h2', {}, 'Agentic Workforce'));
        awSection.appendChild(awHeader);
        renderAgenticWorkforce(data.agenticWorkforce, awSection);
      }
    }

    // CFO View
    if (data.cfoScenarios && data.cfoScenarios.length) {
      var cfoSection = document.getElementById('section-cfo-view');
      if (cfoSection) {
        var cfoHeader = el('div', { className: 'section-header' });
        cfoHeader.appendChild(el('h2', {}, 'CFO What-If Scenarios'));
        cfoHeader.appendChild(el('p', {}, 'Adjust the sliders to model different business scenarios and see projected revenue impacts.'));
        cfoSection.appendChild(cfoHeader);
        renderCFOScenarios(data.cfoScenarios, cfoSection);
      }
    }
  }

  // === INIT ===
  document.addEventListener('DOMContentLoaded', function() {
    var data = window.__DASHBOARD_DATA__;
    if (!data) {
      document.body.innerHTML = '<div style="padding:40px;text-align:center;color:#666;">No dashboard data found.</div>';
      return;
    }

    applyBranding(data.branding);
    buildLogo(data.meta);
    buildNavigation(data.navigation, data.meta);
    renderSections(data);

    // Show first section
    if (data.navigation.length) {
      showSection(data.navigation[0].id);
      var firstLink = document.querySelector('.nav-link');
      if (firstLink) firstLink.classList.add('active');
    }

    // Restore collapsed state from localStorage
    var sidebar = document.getElementById('sidebar');
    var savedCollapsed = false;
    try { savedCollapsed = localStorage.getItem('dashboard-sidebar-collapsed') === 'true'; } catch(e) {}
    if (savedCollapsed && window.innerWidth > 768) {
      sidebar.classList.add('collapsed');
    }

    // Hamburger toggle — icon strip, not hide
    document.getElementById('hamburger-btn').addEventListener('click', function() {
      sidebar.classList.toggle('collapsed');
      try { localStorage.setItem('dashboard-sidebar-collapsed', sidebar.classList.contains('collapsed')); } catch(e) {}
    });

    // Escape key closes drill-down or chat
    document.addEventListener('keydown', function(e) {
      if (e.key === 'Escape') {
        closeDrillDown();
        var panel = document.getElementById('ai-chat-panel');
        if (panel && !panel.classList.contains('ai-chat-hidden')) {
          panel.classList.add('ai-chat-hidden');
        }
      }
    });

    showToast('Dashboard loaded successfully');

    // === AI CHAT WIDGET ===
    initAiChat(data);
  });

  function initAiChat(data) {
    var fab = document.getElementById('ai-chat-fab');
    var panel = document.getElementById('ai-chat-panel');
    var closeBtn = document.getElementById('ai-chat-close');
    var input = document.getElementById('ai-chat-input');
    var sendBtn = document.getElementById('ai-chat-send');
    var messagesEl = document.getElementById('ai-chat-messages');
    var messages = [];
    var isThinking = false;

    var companyName = (data.meta && data.meta.companyName) || 'this company';
    var jobTitle = (data.meta && data.meta.jobTitle) || 'this role';

    function getActiveSection() {
      var active = document.querySelector('.nav-link.active');
      return active ? active.textContent.trim() : 'Overview';
    }

    fab.addEventListener('click', function() {
      panel.classList.toggle('ai-chat-hidden');
      if (!panel.classList.contains('ai-chat-hidden')) {
        input.focus();
      }
    });

    closeBtn.addEventListener('click', function() {
      panel.classList.add('ai-chat-hidden');
    });

    input.addEventListener('keydown', function(e) {
      if (e.key === 'Enter') send();
    });

    sendBtn.addEventListener('click', send);

    function send() {
      var text = input.value.trim();
      if (!text || isThinking) return;
      input.value = '';
      addMessage('user', text);
      isThinking = true;
      showTyping();

      var section = getActiveSection();
      setTimeout(function() {
        removeTyping();
        addMessage('assistant', getAIResponse(text, { companyName: companyName, jobTitle: jobTitle, activeSection: section, dashboardData: data }));
        isThinking = false;
      }, 1500);
    }

    function addMessage(role, content) {
      // Remove placeholder
      var ph = messagesEl.querySelector('.ai-chat-placeholder');
      if (ph) ph.remove();

      messages.push({ role: role, content: content });
      var div = document.createElement('div');
      div.className = 'ai-chat-msg ' + role;
      div.textContent = content;
      messagesEl.appendChild(div);
      messagesEl.scrollTop = messagesEl.scrollHeight;
    }

    function showTyping() {
      var dots = document.createElement('div');
      dots.className = 'ai-chat-typing';
      dots.id = 'ai-chat-typing';
      dots.innerHTML = '<span></span><span></span><span></span>';
      messagesEl.appendChild(dots);
      messagesEl.scrollTop = messagesEl.scrollHeight;
    }

    function removeTyping() {
      var t = document.getElementById('ai-chat-typing');
      if (t) t.remove();
    }
  }

  function getActiveSectionData(context) {
    var data = context.dashboardData;
    var sectionLabel = context.activeSection;
    if (!data || !data.sections) return null;
    // Match by label via navigation
    var navItem = (data.navigation || []).find(function(n) { return n.label === sectionLabel; });
    if (!navItem) return null;
    return data.sections.find(function(s) { return s.id === navItem.id; }) || null;
  }

  function getAIResponse(userMsg, context) {
    var q = userMsg.toLowerCase();
    var section = context.activeSection;
    var company = context.companyName;
    var data = context.dashboardData;
    var sd = getActiveSectionData(context);

    // Section-specific counts
    var metricCount = sd && sd.metrics ? sd.metrics.length : 0;
    var chartCount = sd && sd.charts ? sd.charts.length : 0;
    var tableCount = sd && sd.tables ? sd.tables.length : 0;
    var firstMetric = metricCount > 0 ? sd.metrics[0].label + ' (' + sd.metrics[0].value + ')' : '';
    var firstChart = chartCount > 0 ? sd.charts[0].title : '';

    // CFO section detection
    var isCFO = section.toLowerCase().indexOf('cfo') !== -1 || section.toLowerCase().indexOf('scenario') !== -1;
    var isAgentic = section.toLowerCase().indexOf('agentic') !== -1 || section.toLowerCase().indexOf('workforce') !== -1;

    // Keyword-triggered responses
    if (q.includes('competitor') || q.includes('market')) {
      return 'Looking at the ' + section + ' view for ' + company + ', I can highlight competitive positioning, market share trends, and pricing dynamics shown in the data. Which aspect interests you?';
    }
    if (q.includes('chart') || q.includes('graph') || q.includes('visual')) {
      var chartInfo = firstChart ? ' The \\u201C' + firstChart + '\\u201D chart is a good starting point.' : '';
      return 'The ' + section + ' section has ' + chartCount + ' chart(s).' + chartInfo + ' I can suggest alternative chart types or highlight key data patterns. What would you like to explore?';
    }
    if (q.includes('metric') || q.includes('kpi') || q.includes('number')) {
      var metricInfo = firstMetric ? ' For example, ' + firstMetric + '.' : '';
      return 'There are ' + metricCount + ' KPIs in ' + section + '.' + metricInfo + ' Want me to break down what\\u2019s driving any of these trends?';
    }
    if (q.includes('table') || q.includes('data') || q.includes('record')) {
      return 'The ' + section + ' section includes ' + tableCount + ' data table(s). You can click any row for a drill-down view. Want me to highlight notable patterns in the records?';
    }
    if (q.includes('color') || q.includes('brand') || q.includes('theme') || q.includes('design')) {
      return 'This dashboard uses ' + company + '\\u2019s brand palette. I can suggest adjustments to the color scheme, contrast, or typography. What would you like to change?';
    }
    if (q.includes('export') || q.includes('download') || q.includes('share')) {
      return 'You can download this dashboard as a ZIP or single HTML file from the main application page. The exported file is fully self-contained.';
    }
    if (q.includes('slider') || q.includes('scenario') || q.includes('what-if') || q.includes('forecast')) {
      var scenarioNames = data.cfoScenarios ? data.cfoScenarios.map(function(s) { return s.title; }).join(', ') : 'pricing, headcount, expansion';
      return 'The CFO scenarios let you model different outcomes: ' + scenarioNames + '. Adjust the sliders to see projected revenue impact across quarters. Which scenario would you like to explore?';
    }
    if (q.includes('agent') || q.includes('workforce') || q.includes('ai')) {
      var agentCount = data.agenticWorkforce ? data.agenticWorkforce.length : 0;
      return 'The Agentic Workforce section outlines ' + agentCount + ' planned AI agents designed to augment ' + company + '\\u2019s teams. Want to discuss implementation priorities or team interfaces?';
    }

    // Section-specific fallbacks
    if (isCFO) {
      var scenarioList = data.cfoScenarios ? data.cfoScenarios.map(function(s) { return s.title; }).join(', ') : 'multiple scenarios';
      return 'You\\u2019re viewing the CFO What-If Scenarios: ' + scenarioList + '. Try adjusting the sliders to model revenue impact. Which scenario would you like to dig into?';
    }
    if (isAgentic) {
      var agentFirst = data.agenticWorkforce && data.agenticWorkforce.length > 0 ? data.agenticWorkforce[0].name : 'the first agent';
      return 'The Agentic Workforce roadmap shows planned AI agents for ' + company + '. ' + agentFirst + ' is one example. Want to explore how these agents would interface with specific teams?';
    }

    // Generic dashboard-focused fallbacks
    var fallbacks = [
      'I\\u2019m analyzing the ' + section + ' section \\u2014 ' + metricCount + ' metrics, ' + chartCount + ' charts, ' + tableCount + ' table(s). What catches your eye?',
      'The ' + section + ' view for ' + company + ' shows some interesting patterns.' + (firstMetric ? ' ' + firstMetric + ' stands out.' : '') + ' Want me to break anything down?',
      'I can help interpret the data in ' + section + ' \\u2014 trends in the KPIs, chart patterns, or notable records. What would you like to explore?',
      'Looking at ' + section + ' for ' + company + '.' + (firstChart ? ' The \\u201C' + firstChart + '\\u201D visualization has some notable data points.' : '') + ' What would you like to dig into?'
    ];
    return fallbacks[Math.floor(Math.random() * fallbacks.length)];
  }

})();
`;
}
